# Make Artist Data for Part 2

In [33]:
import pandas as pd
#df = pd.read_csv('data/beatles_test.csv')
#df = pd.read_csv('data/year2009_test.csv')
#df = pd.read_csv('data/year1962_test.csv')
#df = pd.read_csv('data/year2012_2021_test.csv')
df = pd.read_csv('data/year1992_2011_test.csv')

df

,Year,Place,Title,Artist,Featuring,Title_url,Released,Genre 1,Genre 2,Genre 3,Length,Label,Total Labels,Writer 1,Writer 2,Youtube
0,1992,1,End of the Road,Boyz II Men,NaN,/wiki/End_of_the_Road_(Boyz_II_Men_song),1992.0,R&b,NaN,NaN,5:48,LaFace,3.0,"Kenneth ""Babyface"" Edmonds","Antonio ""L.A."" Reid",https://www.youtube.com/watch?v=zDKO6XYXioc
1,1992,2,Baby Got Back,Sir Mix-a-Lot,NaN,/wiki/Baby_Got_Back,1992.0,Hip hop,Dirty rap,Miami bass,4:21,Def American,2.0,Sir Mix-a-Lot,NaN,https://www.youtube.com/watch?v=X53ZSxkQ3Ho
2,1992,3,Jump,Kris Kross,NaN,/wiki/Jump_(Kris_Kross_song),1992.0,Hip hop,NaN,NaN,5:09,Ruffhouse,2.0,Jermaine Dupri,"Joe ""The Butcher"" Nicolo",https://www.youtube.com/watch?v=010KyIQjkTk
3,1992,4,Save the Best for Last,Vanessa Williams,NaN,/wiki/Save_the_Best_for_Last,1992.0,Pop,Soul,NaN,3:40,Wing,2.0,Phil Galdston,Wendy Waldman,https://www.youtube.com/watch?v=5EdmHSTwmWY
4,1992,5,Baby-Baby-Baby,TLC,NaN,/wiki/Baby-Baby-Baby,1992.0,NaN,NaN,NaN,5:15,LaFace,2.0,Kenneth Edmonds,Antonio Reid,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2011,96,Are You Gonna Kiss Me or Not,Thompson Square,NaN,/wiki/Are_You_Gonna_Kiss_Me_or_Not,2010.0,Country,NaN,NaN,3:04,Stoney Creek,1.0,Jim Collins,David Lee Murphy,NaN
1996,2011,97,Animal,Neon Trees,NaN,/wiki/Animal_(Neon_Trees_song),2010.0,Alternative rock,Pop rock,Pop-punk,3:32,Mercury,1.0,Chris Allen,Branden Campbell,NaN
1997,2011,98,You and Tequila,Kenny Chesney,Grace Potter,/wiki/You_and_Tequila,2011.0,Country,NaN,NaN,4:03,BNA,1.0,Matraca Berg,Deana Carter,NaN
1998,2011,99,Colder Weather,Zac Brown Band,NaN,/wiki/Colder_Weather,2010.0,Country,NaN,NaN,4:35,Atlantic,1.0,Zac Brown,Wyatt Durrette,NaN
1999,2011,100,My Last,Big Sean,Chris Brown,/wiki/My_Last,2011.0,Hip hop,R&b,NaN,4:14,GOOD Music,2.0,Sean Anderson,Chris Brown,NaN

In [34]:
artist = df['Artist'].dropna().tolist()
featuring = df['Featuring'].dropna().tolist()
writer1 = df['Writer 1'].dropna().tolist()
writer2 = df['Writer 2'].dropna().tolist()
all_people = [*artist, *featuring, *writer1, *writer2 ]
all_people = sorted(set(all_people))
len(all_people)

2412

In [40]:
#df[df['Artist'] == 'Do']
df[df['Writer 1'] == 'Wasalu Muhammad JacoRudolph Lopez[1]Matthew Santos']

,Year,Place,Title,Artist,Featuring,Title_url,Released,Genre 1,Genre 2,Genre 3,Length,Label,Total Labels,Writer 1,Writer 2,Youtube
1662,2008,63,Superstar,Lupe Fiasco,Matthew Santos,/wiki/Superstar_(Lupe_Fiasco_song),2007.0,Hip hop,NaN,NaN,4:49,1st & 15th,2.0,Wasalu Muhammad JacoRudolph Lopez[1]Matthew Sa...,NaN,https://www.youtube.com/watch?v=hVkBlsgthLg


## Find similarities  (OBS: Maybe make it do it one year at the time! Only comparing people from the same year)
### GoaI: Find out if it is the same person under another name?
I wanna make a training model that I can train with my data. I will make a bunch of list with the following names:
- interesting_pairs # Example: 'BeyoncÃ©' and 'BeyoncÃ© Knowles'. I want this count as the same person. The algorithm should find a bunch of names that could be a potential pseudonym or slightly longer/shorter name.
- approved_list # When ever i manually approve a match, i want the program to remember, so I don't have to do it again.
- ignoring_list # Common names like Max, might pop up alot. So this list automatically remove them from future checks

It should result in a list that I can apply the proper changes to my dataset. So the singer / writers get the real credit.

In [37]:
# Not implemented yet!
#other_connections = [['Lennon','Lennon-McCartney','John Lennon'],['McCartney','Lennon-McCartney','John McCartney']]

interesting_pairs = []

for x in all_people:
    for y in all_people:
        if(x in y and x != y):
            interesting_pairs.append([x,y])
            #print(x, " is similar to ", y)

len(interesting_pairs)
#interesting_pairs

217

In [114]:
# OBS: dont run this, unless you want to reset the lists!
#ignoring_list = [["Train","Meghan Trainor"]]
#approved_list = [['BeyoncÃ©', 'BeyoncÃ© Knowles']]
#list_to_change = []

In [38]:
ignoring_list = load_ignoring_list() # Run the Save / Load part futher down!
approved_list = load_approved_list()
#list_to_change = []
#approved_list

#### Initial scan to remove known cases.

In [39]:
# This function remove everything that already have been scanned before. So we don't have to manually pick them again in the next part

print('Interesting pairs before first sorting: ',len(interesting_pairs))

for x in interesting_pairs.copy():
    if(x in ignoring_list):
        interesting_pairs.remove(x)
    elif(x in approved_list):
        interesting_pairs.remove(x)

print('Interesting pairs affter first sorting: ',len(interesting_pairs))

Interesting pairs before first sorting:  217
Interesting pairs affter first sorting:  116

In [24]:
print("Interesting pairs:",len(interesting_pairs))
print("Approved Words list:",len(approved_list))
print("Ignored Words list:",len(ignoring_list))
#print("List ready for change:",len(list_to_change))

Interesting pairs: 255
Approved Words list: 64
Ignored Words list: 9

In [26]:
print('y = yes, n = no, m = maybe')

for pair in interesting_pairs.copy(): # Can't remove from the same list as we are iterating. So we make a copy
    answer = input(f'Is: {pair[0]} the same as: {pair[1]}?')
    if(answer.lower() == 'y'):
        approved_list.append(pair)
        interesting_pairs.remove(pair)
    elif(answer.lower() == 'n'):
        ignoring_list.append(pair)
        interesting_pairs.remove(pair) 
    elif(answer.lower() == 'm'):
        print('Maybe. Not implemented yet')
    else:
        print('Wrong input')

print('Interesting pairs after second sorting: ',len(interesting_pairs))

y = yes, n = no, m = maybe
Is: Ahmad the same as: Ahmad A. Lewis?m
Maybe. Not implemented yet
Is: Ahmad the same as: Mirwais AhmadzaÃ¯?m
Maybe. Not implemented yet
Is: Akon the same as: Aliaune 'Akon' Thiam?y
Is: Amber the same as: Marie- Claire Cremers (Amber)?y
Is: Amerie the same as: Amerie Rogers?y
Is: Ashanti the same as: Ashanti Douglas?y
Is: Avant the same as: Myron Avant?m
Maybe. Not implemented yet
Is: Baby the same as: Baby Bash?m
Maybe. Not implemented yet
Is: Baby the same as: Baby Boy da Prince?m
Maybe. Not implemented yet
Is: Baby the same as: Babyface?m
Maybe. Not implemented yet
Is: Baby the same as: Bryan "Baby" Williams?m
Maybe. Not implemented yet
Is: Baby the same as: Kenneth "Babyface" Edmonds?n
Is: Baby the same as: Warryn "Baby Dubb" Campbell?m
Maybe. Not implemented yet
Is: Babyface the same as: Kenneth "Babyface" Edmonds?m
Maybe. Not implemented yet
Is: Beck the same as: Walter Becker?n
Is: Black Eyed Peas the same as: The Black Eyed Peas?y
Is: Bobby Simmons the same as: Bobby Simmons Jr.?y
Is: Bon Jovi the same as: Jon Bon Jovi?y
Is: Bone the same as: Bone Thugs-n-Harmony?m
Maybe. Not implemented yet
Is: Bone the same as: Krayzie Bone?m
Maybe. Not implemented yet
Is: Bow Wow the same as: Lil' Bow Wow?y
Is: Branch the same as: Michelle Branch?m
Maybe. Not implemented yet
Is: Brown the same as: Bobby Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Brownstone?n
Is: Brown the same as: Chris Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Darrell Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Donny Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Foxy Brown?m
Maybe. Not implemented yet
Is: Brown the same as: James Brown?m
Maybe. Not implemented yet
Is: Brown the same as: James T. Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Jim "Moose" Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Patrick Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Rodney Browning Cravens?n
Is: Brown the same as: Sleepy Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Terry Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Tom Browne?m
Maybe. Not implemented yet
Is: Brown the same as: V. Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Vincent Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Zac Brown?m
Maybe. Not implemented yet
Is: Brown the same as: Zac Brown Band?m
Maybe. Not implemented yet
Is: Burruss the same as: Kandi Burruss?y
Is: Case the same as: Brandon Casey?n
Is: Case the same as: Brian Casey?n
Is: Case the same as: Case Woodard?m
Maybe. Not implemented yet
Is: Case the same as: Casey Beathard?n
Is: Case the same as: Harry Wayne Casey?n
Is: Cher the same as: Cherine Anderson?m
Maybe. Not implemented yet
Is: Cher the same as: Cherish?n
Is: Cher the same as: Cheryl James?n
Is: Cher the same as: Eagle-Eye Cherry?n
Is: Cornell Haynes the same as: Cornell Haynes Jr.?y
Is: Curtis Jackson the same as: Curtis Jackson III?y
Is: David Lee the same as: David Lee Murphy?y
Is: Dev the same as: Arrested Development?m
Maybe. Not implemented yet
Is: Dev the same as: Devin Tailes?n
Is: Diddy the same as: Diddy â€“ Dirty Money?m
Maybe. Not implemented yet
Is: Diddy the same as: P. Diddy?y
Is: Diddy the same as: Sean "Diddy" Combs?y
Is: Dido the same as: Dido Armstrong?y
Is: Die the same as: Dierks Bentley?m
Maybe. Not implemented yet
Is: Die the same as: Do or Die?m
Maybe. Not implemented yet
Is: Do the same as: 3 Doors Down?m
Maybe. Not implemented yet
Is: Do the same as: Andy Dodd?n
Is: Do the same as: Ashanti Douglas?n
Is: Do the same as: Chris Dooley Jr.?n
Is: Do the same as: Colby O'Donis?m
Maybe. Not implemented yet
Is: Do the same as: Danny O'Donoghue?m
Maybe. Not implemented yet
Is: Do the same as: Do or Die?m
Maybe. Not implemented yet
Is: Do the same as: Dobie Gray?m
Maybe. Not implemented yet
Is: Do the same as: Dolly Parton?n
Is: Do the same as: Dolores O'Riordan?m
Maybe. Not implemented yet
Is: Do the same as: Dominic Thomas?m
Maybe. Not implemented yet
Is: Do the same as: Domino?m
Maybe. Not implemented yet
Is: Do the same as: Don DuBose?n
Is: Do the same as: Don Henley?n
Is: Do the same as: Don Rollins?n
Is: Do the same as: Don Von Tress?n
Is: Do the same as: Donald Custis?m
Maybe. Not implemented yet
Is: Do the same as: Donald DeGrate?m
Maybe. Not implemented yet
Is: Do the same as: Donald DeGrate Jr.?m
Maybe. Not implemented yet
Is: Do the same as: Donald Fagen?m
Maybe. Not implemented yet
Is: Do the same as: Donell Jones?m
Maybe. Not implemented yet
Is: Do the same as: Donna Lewis?m
Maybe. Not implemented yet
Is: Do the same as: Donny Brown?m
Maybe. Not implemented yet
Is: Do the same as: Donovan Bennett?m
Maybe. Not implemented yet
Is: Do the same as: Dorian Moore?m
Maybe. Not implemented yet
Is: Do the same as: Doug Ardito?m
Maybe. Not implemented yet
Is: Do the same as: Doug Corella?m
Maybe. Not implemented yet
Is: Do the same as: Doug Hopkins?a
Abort
Is: Do the same as: Douglas Davis?m
Maybe. Not implemented yet
Is: Do the same as: Dow Brain?m
Maybe. Not implemented yet
Is: Do the same as: Eamon Doyle?m
Maybe. Not implemented yet
Is: Do the same as: Forrest Kline and His Dog?m
Maybe. Not implemented yet
Is: Do the same as: Goo Goo Dolls?n
Is: Do the same as: Jamal "Polow da Don" Jones?n
Is: Do the same as: Nate Dogg?n
Is: Do the same as: No Doubt?n
Is: Do the same as: O'Donoghue?m
Maybe. Not implemented yet
Is: Do the same as: Polow da Don?n
Is: Do the same as: Pussycat Dolls?n
Is: Do the same as: Ralph MacDonald?n
Is: Do the same as: Richie McDonald?n
Is: Do the same as: Snoop Dogg?n
Is: Do the same as: Snoop Doggy Dogg?n
Is: Do the same as: Spin Doctors?n
Is: Do the same as: Teddy Douglas?n
Is: Do the same as: The Pussycat Dolls?n
Is: Do the same as: Tom Douglas?m
Maybe. Not implemented yet
Is: Donald DeGrate the same as: Donald DeGrate Jr.?y
Is: Drake the same as: Drake Cooper?n
Is: Dream the same as: The-Dream?m
Maybe. Not implemented yet
Is: Eamon the same as: Eamon Doyle?y
Is: Eric BenÃ©t the same as: Eric BenÃ©t*?y
Is: Estelle the same as: Estelle Swaray?m
Maybe. Not implemented yet
Is: Evan the same as: Evan Bogart?m
Maybe. Not implemented yet
Is: Evan the same as: Evan Rogers?m
Maybe. Not implemented yet
Is: Evan the same as: Evan Taubenfeld?m
Maybe. Not implemented yet
Is: Evan the same as: Evanescence?n
Is: Evan the same as: Faith Evans?n
Is: Evan the same as: Lauren Evans?n
Is: Evan the same as: Tom Evans?n
Is: Eve the same as: Eve 6?m
Maybe. Not implemented yet
Is: Eve the same as: Eve Jeffers?m
Maybe. Not implemented yet
Is: Eve the same as: Everclear?n
Is: Eve the same as: Everlast?n
Is: Eve the same as: Everything but the Girl?n
Is: Eve the same as: JÃ¶rg Evers?n
Is: Five the same as: Five for Fighting?m
Maybe. Not implemented yet
Is: Five the same as: Hi-Five?m
Maybe. Not implemented yet
Is: Five the same as: The Click Five?m
Maybe. Not implemented yet
Is: Frampton the same as: Andrew Frampton?y
Is: Frampton the same as: Peter Frampton?y
Is: Hanson the same as: Cody Hanson?m
Maybe. Not implemented yet
Is: Hanson the same as: Isaac Hanson?m
Maybe. Not implemented yet
Is: Hanson the same as: Taylor Hanson?m
Maybe. Not implemented yet
Is: Heavy D the same as: Heavy D & the Boyz?y
Is: Houston the same as: Houston Summers?m
Maybe. Not implemented yet
Is: Houston the same as: Jordan Houston?m
Maybe. Not implemented yet
Is: Houston the same as: Whitney Houston?m
Maybe. Not implemented yet
Is: Humphrey the same as: Montay Humphrey?m
Maybe. Not implemented yet
Is: James Smith the same as: Trevor James Smith Jr.?y
Is: Janet the same as: Janet Jackson?m
Maybe. Not implemented yet
Is: Jaron the same as: Jaron Alston?m
Maybe. Not implemented yet
Is: Jaron the same as: Jaron Lowenstein?m
Maybe. Not implemented yet
Is: Jeezy the same as: Young Jeezy?m
Maybe. Not implemented yet
Is: Jewel the same as: Jewel Kilcher?m
Maybe. Not implemented yet
Is: JoJo the same as: K-Ci & JoJo?m
Maybe. Not implemented yet
Is: Joe the same as: Billie Joe Armstrong?m
Maybe. Not implemented yet
Is: Joe the same as: Billy Joel?n
Is: Joe the same as: Fat Joe?m
Maybe. Not implemented yet
Is: Joe the same as: Harve "Joe Hooker" Pierre?m
Maybe. Not implemented yet

Is: Joe the same as: Joe "The Butcher" Nicolo?m
Maybe. Not implemented yet
Is: Joe the same as: Joe Carpenter?m
Maybe. Not implemented yet
Is: Joe the same as: Joe Elliott?m
Maybe. Not implemented yet
Is: Joe the same as: Joe Kent?m
Maybe. Not implemented yet
Is: Joe the same as: Joe King?m
Maybe. Not implemented yet
Is: Joe the same as: Joe Perry?m
Maybe. Not implemented yet
Is: Joe the same as: Joe Public?m
Maybe. Not implemented yet
Is: Joe the same as: Joe Rich?m
Maybe. Not implemented yet
Is: Joe the same as: Joe Thomas?m
Maybe. Not implemented yet
Is: Joe the same as: Joel Hailey?n
Is: Joe the same as: Joey Lawrence?n
Is: Joe the same as: Joey McIntyre?n
Is: Joe the same as: Joey McIntyreJoseph Carrier?n
Is: Joe the same as: Ugly Kid Joe?m
Maybe. Not implemented yet
Is: Joey McIntyre the same as: Joey McIntyreJoseph Carrier?m
Maybe. Not implemented yet
Is: K-Ci the same as: K-Ci & JoJo?y
Is: Kandi the same as: Kandi Burruss?m
Maybe. Not implemented yet
Is: Kay Gee the same as: Kier "Kay Gee" Gist?y
Is: Kelis the same as: Kelis Rogers-Jones?y
Is: Lea the same as: Edmond Leary?n
Is: Len the same as: Annie Lennox?n
Is: Len the same as: Lenny Kravitz?m
Maybe. Not implemented yet
Is: Len the same as: Steven "Lenky" Marsden?m
Maybe. Not implemented yet
Is: Len the same as: Stuart McLennen?m
Maybe. Not implemented yet
Is: Lil Jon the same as: Lil Jon & The East Side Boyz?y
Is: Lil Jon the same as: Lil Jon & the East Side Boyz?y
Is: Lloyd the same as: C. Lloyd?m
Maybe. Not implemented yet
Is: Lloyd the same as: Christopher Lloyd?m
Maybe. Not implemented yet
Is: Lloyd the same as: Lloyd Banks?m
Maybe. Not implemented yet
Is: Lloyd the same as: Lloyd Polite?m
Maybe. Not implemented yet
Is: Luke the same as: Dr. Luke?m
Maybe. Not implemented yet
Is: Luke the same as: Luke Bryan?m
Maybe. Not implemented yet
Is: Luke the same as: Luke Gottwald?m
Maybe. Not implemented yet
Is: Luke the same as: Luke Laird?m
Maybe. Not implemented yet
Is: Lumidee the same as: Lumidee CedeÃ±o?y
Is: M.I.A. the same as: Maya "M.I.A." Arulpragasam?y
Is: Manuel Seal the same as: Manuel Seal Jr.?y
Is: Mario the same as: Mario Winans?m
Maybe. Not implemented yet
Is: Matthew Santos the same as: Wasalu Muhammad JacoRudolph Lopez[1]Matthew Santos?m
Maybe. Not implemented yet
Is: Miguel the same as: Miguel A. Morejon?m
Maybe. Not implemented yet
Is: Miguel the same as: Miguel Morejon?m
Maybe. Not implemented yet
Is: Miller the same as: Bruce Miller?m
Maybe. Not implemented yet
Is: Miller the same as: Byron Lee Miller?m
Maybe. Not implemented yet
Is: Miller the same as: Ken Miller?m
Maybe. Not implemented yet
Is: Miller the same as: Lee Thomas Miller?m
Maybe. Not implemented yet
Is: Miller the same as: Percy Miller?m
Maybe. Not implemented yet
Is: Miller the same as: Quentin Miller?m
Maybe. Not implemented yet
Is: Miller the same as: Steve Miller?m
Maybe. Not implemented yet
Is: Mims the same as: Shawn Mims?m
Maybe. Not implemented yet
Is: Monica the same as: Monica Arnold?
Wrong input
Is: Nas the same as: Freak Nasty?n
Is: Nas the same as: Johnny Nash?n
Is: Nas the same as: Nasir Jones?m
Maybe. Not implemented yet
Is: Nas the same as: T. Nash?n
Is: Nas the same as: Terius Nash?n
Is: Natalie the same as: Natalie Albino?m
Maybe. Not implemented yet
Is: Natalie the same as: Natalie Alvarado?m
Maybe. Not implemented yet
Is: Natalie the same as: Natalie Merchant?m
Maybe. Not implemented yet
Is: Ne-Yo the same as: Shaffer "Ne-Yo" Smith?y
Is: Nelly the same as: Nelly Furtado?n
Is: Nicole the same as: Nicole Albino?m
Maybe. Not implemented yet
Is: O'Donoghue the same as: Danny O'Donoghue?m
Maybe. Not implemented yet
Is: Pharrell the same as: Pharrell Williams?y
Is: Polow da Don the same as: Jamal "Polow da Don" Jones?y
Is: Prince the same as: Baby Boy da Prince?m
Maybe. Not implemented yet
Is: Prince the same as: DJ Jazzy Jeff & The Fresh Prince?n
Is: Pussycat Dolls the same as: The Pussycat Dolls?y
Is: Queen the same as: Queen Latifah?n
Is: Quickmix the same as: Frank "Quickmix" Hassas?y
Is: Rome the same as: Anthony "Romeo" Santos?n
Is: Rome the same as: Antonio Romero Monge?m
Maybe. Not implemented yet
Is: Rome the same as: Lil' Romeo?n
Is: Santana the same as: Juelz Santana?m
Maybe. Not implemented yet
Is: Seal the same as: Manuel Seal?y
Is: Seal the same as: Manuel Seal Jr.?y
Is: Sean P the same as: Sean Paul?m
Maybe. Not implemented yet
Is: Sean P the same as: Sean Paul Henriques?m
Maybe. Not implemented yet
Is: Sean P the same as: Sean Paul Joseph?m
Maybe. Not implemented yet
Is: Sean Paul the same as: Sean Paul Henriques?m
Maybe. Not implemented yet
Is: Sean Paul the same as: Sean Paul Joseph?m
Maybe. Not implemented yet
Is: Shamar Daugherty the same as: Shamar DaughertyHoward Bailey?m
Maybe. Not implemented yet
Is: Silk the same as: Phillip "Silky" White?n
Is: Silk the same as: Steve "Silk" Hurley?m
Maybe. Not implemented yet
Is: Snoop Dogg the same as: Snoop Doggy Dogg?y
Is: Snow the same as: Snow Patrol?m
Maybe. Not implemented yet
Is: Snow the same as: Tom Snow?m
Maybe. Not implemented yet
Is: Static Major the same as: Stephen "Static Major" Garrett?y
Is: Sting the same as: Sting (English)?y
Is: Terry Lewis the same as: Jimmy Jam and Terry Lewis?y
Is: The Verve the same as: The Verve Pipe?m
Maybe. Not implemented yet
Is: Todd Thomas the same as: Speech (Todd Thomas)?y
Is: Tom Petty the same as: Tom Petty and the Heartbreakers?y
Is: Trevor Smith the same as: Trevor Smith Jr.?y
Is: Tyrese the same as: Tyrese Gibson?m
Maybe. Not implemented yet
Is: Usher the same as: Usher Raymond?y
Is: Usher Raymond the same as: Usher Raymond IV?y
Is: Van Halen the same as: Eddie Van Halen?y
Is: Vassal Benford the same as: Vassal Benford III?y
Is: Warren G the same as: Warren Griffin?y
Is: Warren G the same as: Warren Griffin III?y
Is: Warren Griffin the same as: Warren Griffin III?y
Is: William Ray Norwood the same as: William Ray Norwood Jr.?y
Is: Yung the same as: Yung Berg?m
Maybe. Not implemented yet
Is: Yung the same as: Yung Joc?m
Maybe. Not implemented yet
Interesting pairs after second sorting:  144

In [ ]:
# Wasalu Muhammad JacoRudolph Lopez[1]Matthew Santos
#Joey McIntyreJoseph Carrier
#Shamar DaughertyHoward Bailey

In [27]:
print("Interesting pairs:",len(interesting_pairs))
print("Approved:",len(approved_list))
print("Ignored:",len(ignoring_list))
#print("List ready for change:",len(list_to_change))

Interesting pairs: 144
Approved: 116
Ignored: 68

## Save / Load the wordlists

In [28]:
import pandas as pd
import csv

def save_approved_list(list):
    df = pd.DataFrame(list,columns=['Replacement','Key Word'])
    df.to_csv('data/similar/approved_list.csv', index = False, header=True)
    
def save_ignoring_list(list):
    df = pd.DataFrame(list,columns=['Replacement','Key Word'])
    df.to_csv('data/similar/ignoring_list.csv', index = False, header=True)


def load_approved_list():
    with open('data/similar/approved_list.csv', 'r') as f: 
        return list(csv.reader(f))[1:] # Skip header

def load_ignoring_list():
    with open('data/similar/ignoring_list.csv', 'r') as f: 
        return list(csv.reader(f))[1:] # Skip header

In [29]:
save_approved_list(approved_list)
save_ignoring_list(ignoring_list)

In [64]:
#print("Size of approved list:",len(load_approved_list()))

### Testing concatenating and groupby

In [295]:
data1 = {'Name':['Tom', 'Jonas', 'Peter'],
        'Money':[100, 100, 100],
        'Debt':[50,50,50]}

data2 = {'Name':['Tom', 'Jonas', 'Peter'],
        'Money':[50, 100, 150],
        'Debt':[100,50,0]}
 
# Create DataFrame
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [297]:
df3 = pd.concat([df1, df2], ignore_index=True)
df3

    Name  Money  Debt
0    Tom    100    50
1  Jonas    100    50
2  Peter    100    50
3    Tom     50   100
4  Jonas    100    50
5  Peter    150     0

In [299]:
df3.groupby(['Name']).sum().reset_index()

    Name  Money  Debt
0  Jonas    200   100
1  Peter    250    50
2    Tom    150   150

## Convert from song to a list of artists

In [120]:
def convert_artist_data_into_df(artists_list):
    data_list = []
    for name in artists_list:
        
        # Might be two names associated with a group. Like Sonny & Cher. They should both individually get credits.
        actual_name = check_approved_list(name)
        
        
        main_artist = len(df[df['Artist'] == name])
        featuring_artist = len(df[df['Featuring'] == name])
        writer = len(df[df['Writer 1'] == name]) + len(df[df['Writer 2'] == name])
        
        for x in actual_name:
            data_list.append([x, main_artist, featuring_artist, writer])
    
    # groupby will merge the duplicates. So each artists only have one line, with all their accreditations
    new_df = pd.DataFrame(data_list, columns= ['Name', 'Main Artist' ,'Featuring Artist', 'Writer'] ) 
    return new_df.groupby(['Name']).sum().reset_index()


def check_approved_list(name):
    name_list = [x[0] for x in approved_list if name == x[1]]
        
    if(len(name_list) == 0):
        name_list = [name]
            
    return name_list


#check_approved_list("Lil Baby and Lil Durk")

In [121]:
df_to_csv = convert_artist_data_into_df(all_people)
#df_to_csv = convert_artist_data_into_df(all_people).sort_values("Main Artist", ascending=False).reset_index(drop=True)

df_to_csv

                     Name  Main Artist  Featuring Artist  Writer
0                2 Chainz            2                 2       0
1               21 Savage            2                 4       0
2                24kGoldn            2                 0       0
3                 42 Dugg            0                 1       0
4     5 Seconds of Summer            4                 0       0
...                   ...          ...               ...     ...
1218                 Zedd            4                 1       0
1219               busbee            0                 0       2
1220         iLoveMemphis            1                 0       0
1221         soFLY & Nius            0                 0       1
1222            will.i.am            2                 1       0

[1223 rows x 4 columns]

## Went from 1280 names to 1223. Good start!

In [50]:
df_to_csv.to_csv('data/artist_2012_2021_test.csv', index = False, header=True)

In [418]:
df_artists = pd.read_csv('data/artist_2012_2021_test.csv')
df_artists

                     Name  Main Artist  Featuring Artist  Writer
0                2 Chainz            2                 2       0
1               21 Savage            2                 4       0
2                24kGoldn            2                 0       0
3                 42 Dugg            0                 1       0
4     5 Seconds of Summer            4                 0       0
...                   ...          ...               ...     ...
1227                 Zedd            4                 1       0
1228               busbee            0                 0       2
1229         iLoveMemphis            1                 0       0
1230         soFLY & Nius            0                 0       1
1231            will.i.am            2                 1       0

[1232 rows x 4 columns]

## Clean the approved and ignoring lists. (Seems to be some doubles entries, which will result in getting counted twice!)

In [101]:
test_approved = load_approved_list()
test_ignoring = load_ignoring_list()

In [103]:

def cleanup_approved_list(list):
    new_list = []
    for x in list:
            if(x not in new_list):
                new_list.append(x)
    return sorted(new_list)
    
#print(len(new_list))        
#sorted(new_list)[:20]

In [107]:
print("Approved before cleanup:",len(test_approved))
print("After:",len(cleanup_approved_list(test_approved)))

Approved before cleanup: 107
After: 64

In [105]:
print("Ignoring before cleanup:",len(test_ignoring))
print("After:",len(cleanup_approved_list(test_ignoring)))

Ignoring before cleanup: 16
After: 9

### Found some duplicates, which corrupts the data. So let's save the now 'cleaned' lists

In [111]:
clean_approved = cleanup_approved_list(test_approved)
clean_ignored = cleanup_approved_list(test_ignoring)

save_approved_list(clean_approved)
save_ignoring_list(clean_ignored)

print(len(load_approved_list()))
print(len(load_ignoring_list()))

64
9